# Generated by Django 5.0.2 on 2024-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='job_end',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='job_start',
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_time',
            field=models.CharField(choices=[('08:00 - 09:30', '08:00 - 09:30'), ('09:35 - 11:00', '09:35 - 11:00'), ('11:10 - 12:00', '11:10 - 12:00'), ('13:00 - 14:30', '13:00 - 14:30'), ('14:35 - 16:40', '14:35 - 16:40')], max_length=255),
        ),
    ]
